[package]
name = "corn_stats"
version = "0.1.0"
edition = "2024"

[dependencies]
# GTK3 stack (konsisten)
appindicator3 = "0.3.0"

# System metrics
sysinfo = "0.38.1"
procfs = "0.18"
gtk = "0.18.2"
glib = "0.21.5"
